version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo

jobs:
  install:
    executor: node
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: "~"
          paths:
            - repo

  lint:
    executor: node
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: Run linter script
          command: yarn lint

  build:
    executor: node
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: Build production
          command: yarn build

workflows:
  version: 2
  default:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
